const siteConfig = {
  name: "Podgorica Car Rental",
  tagline: "Drive from Montenegro's Capital",
  domain: "carrentalpodgorica.com",
  phone: "",
  email: "info@carrentalpodgorica.com",
  address: "Trg Republike, Podgorica, 81000",

  hero: {
    headline: "Podgorica Car Rental, Montenegro's Capital",
    subheadline: "Pick up at Podgorica Airport, gateway to Durmitor, Lake Skadar, and the Adriatic coast.",
    image: "/img/hero-podgorica.webp",
  },

  cars: [
    {
      id: 1,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The low-maintenance coast-runner for a fortnight-long Podgorica base",
      lede: "Light on fuel, cheap to park at the pickup location, and comfortable on the motorway push to Podgorica or Žabljak.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples on a two-week stay", "Day-trippers to Cetinje and Njeguši", "Shoppers at Risan Roman mosaics"],
      suitability: "A pair settling in Podgorica for ten to fourteen days, with regular day-trips out to Cetinje, Risan and the Lake Skadar shore, simple to park, forgiving on petrol.",
      regional: "Handles the Podgorica–Cetinje climb in third gear without drama, threads the narrow waterfront through outlying villages, and the 5.3 L/100 km petrol keeps the fuel bill predictable over a multi-week hire.",
    },
    {
      id: 2,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Diesel mid-size for the Podgorica → Dubrovnik and Podgorica → Durmitor runs",
      lede: "Long-legged BlueHDi + auto box built for the 3-hour push up to Žabljak or the cross-border drive to Trebinje and Mostar.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission","Adaptive Cruise","Dual-Zone Climate","Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: true,
      bestFor: ["Cross-border road-trippers","Durmitor weekenders","Four adults with full luggage"],
      suitability: "The mid-size diesel picks for anyone pairing a Podgorica base with multi-day drives inland, auto gearbox and cruise control earn their keep on the Podgorica motorway.",
      regional: "Cruises the Smokovac–Mateševo motorway section effortlessly, swallows a week of hiking kit bound for Žabljak, and covers the Podgorica → Dubrovnik via Debeli Brijeg run on half a tank.",
    },
    {
      id: 3,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest-boot French mid-size, built for long-stay loads and lake trips",
      lede: "434-litre boot, quiet diesel cruising, sofa-soft damping, the mid-size wagon pick for a month in the bay with regular excursions out.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Long-stay renters","Skadar Lake day-trippers","Families visiting monasteries"],
      suitability: "Renters who want more than a hatchback's packing space without the length of a full estate, ideal for Skadar Lake fishing kit, Cetinje monastery day-bags and a cool-box for the drive home.",
      regional: "The long-travel suspension shrugs off the patchy bitumen on the old Podgorica–Budva road, the dCi diesel sips on the Sozina tunnel run, and the generous boot takes two weeks of family kit plus the laundry bag you pick up in Prčanj.",
    },
    {
      id: 4,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised-ride crossover for the gravel approach to Njeguši and Lovćen",
      lede: "A slightly higher-riding alternative to a hatchback, takes the rutted spur roads around Njeguši and the Lovćen back approaches without scraping.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height","Apple CarPlay","Reversing Camera","Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Weekend trippers to Njeguši","Durmitor day-trippers","Photographers chasing ridge viewpoints"],
      suitability: "Renters who want crossover sight-lines and a bit of ground clearance for the side-roads around Podgorica's upper bay and the Lovćen approach, without paying full-SUV money.",
      regional: "Higher seating position means easier viewing over region parapet walls, the 182 mm ride height clears the stone ruts on the old Njeguši ham-smoker lane, and the 352-litre boot handles a family's Durmitor hiking gear without folding seats.",
    },
    {
      id: 5,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "DSG diesel all-rounder, calm cruising for the E80 and multi-day loops",
      lede: "The rational default for a renter mixing a Podgorica base with long inland drives, refined, quick enough, and economical on the motorway.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing coast and canyon", "Business travellers on week-long hires", "Drivers planning the BiH or Croatia border run"],
      suitability: "The default mid-size for renters who want one car that will do the Podgorica Old Town perimeter on day one and the Smokovac-Mateševo motorway on day four without complaint.",
      regional: "DSG picks the right ratio on the Podgorica–Lovćen hairpins without any thinking, the 2.0 TDI holds 130 km/h on the motorway section up to Podgorica at 4.3 L/100 km, and the cabin quiet makes the 3-hour push to Žabljak genuinely relaxing.",
    },
    {
      id: 6,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Postage-stamp city car for a short Podgorica stay, slots between delivery vans",
      lede: "Tiny footprint, sunroof, hybrid-assisted 1.0, the pick for a two- or three-night Podgorica anchor when multi-day drives aren't on the schedule.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Short city-base stays", "Solo visitors on a shoestring", "Photographers doing short hops"],
      suitability: "Two or three nights in Podgorica with short afternoon hops to Perast and Prčanj, the 500 parks where mid-size cars wave and drive past.",
      regional: "The 3.57 m length is the deciding factor: it fits the stepped terrace parking on the nearby villages waterfront and the shoulder-wide gap outside the Sea Gate that a Clio can't. Underpowered for the Lovćen climb, so pair with cable-car transfers or keep within bay limits.",
    },
    {
      id: 7,
      slug: "citroen-c3",
      typeGroup: "economy",
      name: "Citroen C3",
      category: "Economy",
      tagline: "Softest small hatch for the broken Podgorica–Risan stretch and back-road detours",
      lede: "Advanced Comfort dampers iron out the patched tarmac on the old bay road, the gentlest small car to park at the Podgorica bastions overnight.",
      price: 27,
      image: "/img/fleet/citroen-c3.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Advanced Comfort Seats","Bluetooth Audio","USB Charging","Lane Departure Warning"],
      details: {
        engine: "1.2 PureTech 3-cyl petrol",
        power: "83 hp",
        consumption: "5.5 L/100 km",
        bootSize: "300 L",
        length: "3,996 mm",
        topSpeed: "175 km/h",
        acceleration: "13.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Slow-touring couples","Back-road explorers","Renters prone to motion sickness"],
      suitability: "The comfort-first pick for a week in Podgorica with daily slow-paced detours, Risan's Roman mosaics, the Gornja Lastva hamlet above Tivat, the loop back through nearby villages.",
      regional: "The progressive hydraulic bump stops make the potholed stretch from Risan to Perast feel a size-class quieter, the low-stress 83 hp motor suits the 50 km/h bay-road limits, and the 4-metre length slots into any Old Town bastion bay.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Pick up at Podgorica Airport (TGD) arrivals — the supplier meets you with your name on a sign." },
    { icon: "shield-check", title: "Insurance Options", description: "Free Minimum (third-party) cover on every booking — Basic from €8/day, Full from €10/day, no-deposit Full Plus from €18/day." },
    { icon: "clock", title: "24/7 Booking Support", description: "Booking help around the clock; roadside assistance is provided by the rental supplier." },
    { icon: "ban", title: "No Credit Card Needed", description: "Every car on the platform is bookable without a credit card — pay by cash, debit card or crypto." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "On selected cars (around 176 of approximately 380): refund of advance payment if you cancel more than 24 hours before pickup." },
    { icon: "globe", title: "Cross-Border", description: "Paid cross-border permit at three tiers — neighbours, including Albania & Kosovo, or all-EU + Switzerland." },
  ],

  testimonials: [
    { name: "Erik & Marte Solberg", location: "Oslo, Norway", text: "We flew into TGD specifically to hike Durmitor and walk the rim of Tara Canyon. The 4x4 was ready in minutes and handled the mountain roads to Zabljak without a single complaint. Booking was simple and the price was better than anything we found back home.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Lukas Berger", location: "Vienna, Austria", text: "Solo road trip from Podgorica Airport up through Moraca Canyon to Ostrog Monastery, one of the most dramatic drives I've ever done. The car was immaculate and picking it up at TGD took less than 10 minutes. I'll use this service every time I fly Wizz Air into Montenegro.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Beatriz & Joana", location: "Lisbon, Portugal", text: "We booked a beach trip but ended up spending two days exploring Lake Skadar wine villages and somehow found ourselves on a mountain road above Cetinje at sunset. Best accidental detour ever. The car made it all possible and the booking was completely stress-free.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off at a different location?", a: "Yes, one-way rentals are supported across 28+ delivery points in Montenegro. Choose different pickup and dropoff locations during booking; some routes carry a small relocation fee." },
    { q: "What documents do I need?", a: "A valid driving licence and passport or ID. Most cars accept cash, debit card or crypto for payment \u2014 a credit card is not required on any booking on the platform. International Driving Permit may be needed for non-EU licences depending on the supplier." },
    { q: "Can I drive to Serbia or Albania?", a: "Yes \u2014 cross-border travel is sold as a paid permit at three tiers: (1) Croatia, Bosnia & Herzegovina and Serbia (no Green Card needed); (2) the same plus Albania and Kosovo (Green Card provided); (3) Albania, Kosovo, Croatia, Bosnia, Serbia, Macedonia, all EU countries and Switzerland (Green Card provided). The right tier for your trip is shown at checkout." },
    { q: "Is there a minimum age?", a: "Age and required driving experience vary by vehicle \u2014 the lowest cars on the platform start from 18+ years old with 1+ years driving experience. Filter by your age and experience to see the cars available to you." },
    { q: "What's included in the price?", a: "Every booking includes the free Minimum (third-party liability) cover with a typical \u20AC100 deposit, plus a free second driver and VAT. Insurance upgrades are paid extras: Basic from \u20AC8/day, Full from \u20AC10/day, and a no-deposit Full Plus from \u20AC18/day. Unlimited mileage is included on most cars (376 of around 380)." },
    { q: "How does pickup work at TGD?", a: "Podgorica Airport (TGD) is a compact single-terminal building. The supplier meets you in the arrivals hall holding a board with your name, and the car is parked just outside the terminal. No shuttle is involved at most pickup points." },
    { q: "Can I add a child seat or other extras?", a: "Yes. Child seats (infant, toddler and booster), additional drivers, roof racks, ski racks, Winter Pack, theft protection, personal accident insurance, wireless hotspot and SIM cards can all be added at booking. Tick the extras you need before confirming and the price is shown up front." },
    { q: "Can I cancel my booking?", a: "Free cancellation is available on selected cars (around 176 of ~380, marked in search). On those cars, the full advance payment is refunded if you cancel more than 24 hours before pickup; cancellations within 24 hours are non-refundable." },
    { q: "Is a deposit required?", a: "Most cars hold a \u20AC100 deposit at pickup. 47 cars on the platform require no deposit, and a further 124 offer a no-deposit option as a paid service. Choosing the Full Plus insurance tier (from \u20AC18/day) also waives the deposit." },
    { q: "What happens if I exceed the mileage limit?", a: "Unlimited mileage is included on the vast majority of cars (376 of ~380). For the few cars with a mileage limit, an additional charge per extra kilometre applies \u2014 shown on the listing before you book." },
    { q: "Do I need snow chains for mountain roads?", a: "From November to March, winter tyres or snow chains are legally required on mountain roads above 1,000 m in Montenegro, including the road to \u017Dabljak and Durmitor National Park. The supplier may add a Winter Pack to the booking on request." },
    { q: "How much is the down payment?", a: "An advance payment is taken when you confirm the booking; the remaining balance is paid to the supplier at pickup. The exact split is shown on each car's checkout page before you commit." },
    { q: "Can I rent without a credit card?", a: "Yes \u2014 every car on the platform can be booked without a credit card. Cash, debit card and crypto are accepted at the supplier." },
  ],

  locations: [
    { name: "Podgorica Airport", tag: "Most Popular" },
    { name: "City Centre", tag: "" },
    { name: "Millennium Bridge Area", tag: "" },
  ],

  destinations: [
    { name: "Plantaže Wineries", slug: "blog/podgorica-wineries-plantaze", tag: "15 min drive", desc: "Europe's largest single vineyard plus the Šipčanik wine tunnel carved from an old underground aircraft hangar.", image: "/img/blog-podgorica-wineries-plantaze.webp" },
    { name: "Gorica Hill", slug: "blog/gorica-hill-walk", tag: "City centre", desc: "The wooded hill the capital takes its name from, trails, a WWII memorial, and a 360° view of the Zeta plain.", image: "/img/blog-gorica-hill-walk.webp" },
    { name: "Rijeka Crnojevića", slug: "blog/podgorica-rijeka-crnojevica-drive", tag: "Pavlova Strana", desc: "Montenegro's most-photographed viewpoint, the Pavlova Strana horseshoe bend above Lake Skadar.", image: "/img/blog-podgorica-rijeka-crnojevica-drive.webp" },
    { name: "Stara Varoš", slug: "blog/stara-varos-podgorica-ottoman-quarter", tag: "Old quarter", desc: "Podgorica's Ottoman-era quarter, the clock tower, the Osmanagić mosque, and the lanes that survived the wars.", image: "/img/blog-stara-varos-podgorica-ottoman-quarter.webp" },
    { name: "Nikšić & Ostrog", slug: "blog/niksic-beer-lake-loop", tag: "Day loop", desc: "Montenegro's second city, the brewery behind Nikšićko pivo, a swim at Krupac, and Ostrog on the drive back.", image: "/img/blog-niksic-beer-lake-loop.webp" },
    { name: "Komovi Mountains", slug: "blog/komovi-mountains-berane-road", tag: "Wild east", desc: "The twin pyramids of Kom Kučki and Kom Vasojevićki above 2,400 m, a long mountain-road day toward Berane.", image: "/img/blog-komovi-mountains-berane-road.webp" },
    { name: "Millennium Bridge", slug: "blog/podgorica-millennium-bridge-new-city", tag: "New city", desc: "The cable-stayed bridge over the Morača, the cathedral of Hristovo Vaskrsenje, and where to park to see all three.", image: "/img/blog-podgorica-millennium-bridge-new-city.webp" },
    { name: "Tuzi", slug: "blog/tuzi-albanian-border-short-hop", tag: "15 km south", desc: "Fifteen kilometres from the capital and a different Montenegro, Malësia mountains, Albanian bakeries, Hani i Hotit crossing.", image: "/img/blog-tuzi-albanian-border-short-hop.webp" },
  ],
};

export default siteConfig;
