const siteConfig = {
  name: "Budva Car Hire",
  tagline: "Drive the Montenegrin Riviera",
  domain: "budvacarhire.com",
  phone: "",
  email: "info@budvacarhire.com",
  address: "Budva, Montenegro",

  hero: {
    headline: "Budva Car Hire — Drive the Riviera",
    subheadline: "Rent a car in Budva from Tivat Airport (22 km). Beaches, Old Town, Sveti Stefan — all within reach.",
    image: "/img/hero-budva.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Tivat Airport Pickup", description: "Tivat Airport sits 22 km up the coast from Budva. Your agent is waiting at arrivals — one coast road drive and you're parking on the riviera." },
    { icon: "shield-check", title: "Full Insurance", description: "CDW and theft cover included as standard. Upgrade to zero excess if you want total peace of mind on narrow coastal lanes and tight beach car parks." },
    { icon: "clock", title: "24/7 Support", description: "Left your lights on at Jaz Beach car park? Locked your keys in at Mogren? Call us any hour — we know every car park on this riviera." },
    { icon: "ban", title: "No Hidden Fees", description: "One number at booking. That same number at pickup. VAT, mileage, and beach-town fuel policy are all baked in — nothing added at the counter." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Summer weather on the riviera shifts fast, and festival dates change. Cancel free up to 24 hours before your pickup and get every cent refunded." },
    { icon: "globe", title: "Cross-Border Ready", description: "Dubrovnik is 2.5 hours north via Debeli Brijeg. The Albanian border is closer from Budva than from anywhere else on the riviera. Green card sorted at booking." },
  ],

  testimonials: [
    { name: "Aoife & Conor", location: "Dublin, Ireland", text: "We drove from Jaz Beach to Sveti Stefan on our first morning and couldn't believe the views. Stopped at Bečići for lunch, made it to the Sveti Stefan viewpoint before sunset. The car meant we could dodge the buses and go at our own pace. Would absolutely book again.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Erik, Jonas & Linn", location: "Stockholm, Sweden", text: "Three of us rented for five nights — Top Hill one evening, Trocadero the next, then a road trip south to Petrovac for a slower afternoon. Having a car meant no waiting for taxis at 2am. The agent at Tivat was quick and the car was spotless. Exactly what we needed.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Heidi & Walter", location: "Zürich, Switzerland", text: "We prefer quieter roads and olive groves to beach clubs. The car took us south to Petrovac, through the old village lanes above Budva, and along the coast at our own gentle pace. The old town in the evenings was magical. A very well organised rental from start to finish.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need to rent?", a: "You'll need a full driving licence with Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence is from a country that uses a non-Latin script, bring an International Driving Permit as well. Photocopies and digital-only licences are not accepted at pickup." },
    { q: "Can I drive to Croatia or Albania?", a: "Yes. Cross-border travel is permitted to Croatia, Bosnia, Albania, Kosovo, and Serbia. The Dubrovnik day trip via Debeli Brijeg is one of the most popular runs from Budva — about 2.5 hours each way. Just flag the countries at booking and the Green Card is prepared for you." },
    { q: "Is there a minimum age to rent?", a: "Age and licence experience requirements vary by vehicle class and are listed clearly in each car's details when you search. Younger drivers may see a small daily supplement depending on the model." },
    { q: "What's actually included in the price?", a: "Third-party liability insurance and CDW come standard on most cars. VAT, a roadside safety kit, and a transparent fuel policy are included too. Mileage terms differ per vehicle — check the car listing. Zero-excess cover and extras like child seats can be added at booking." },
    { q: "How does pickup work at Tivat Airport?", a: "Your agent meets you at Tivat Airport arrivals hall. The 22 km coast road to Budva takes around 25 minutes depending on summer traffic. No shuttle, no waiting around — the car is parked right outside the terminal." },
    { q: "Can I return the car somewhere different?", a: "One-way rentals are available across 28+ towns and cities in Montenegro. Pick up at Tivat, drop off in Budva, or vice versa — just select different locations when you book." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days in advance. A 6% processing fee applies on all cancellations regardless of timing." },
    { q: "Do I need to pay a deposit?", a: "It depends on the vehicle. Deposits typically fall between €100 and €500 for most riviera rentals. Some cars require no deposit at all. Where one applies, it sits on the main driver's physical credit card and is released when the car is returned undamaged." },
    { q: "What if I go over my mileage allowance?", a: "Vehicles with a set mileage cap charge a per-kilometre fee for any distance above the limit. The exact overage rate is shown in the car details before you confirm — no surprises." },
    { q: "Is the price I see the price I pay?", a: "Yes. All taxes and standard fees are folded into the booking price. There is no fuel surcharge, airport levy, or desk fee added when you collect the car." },
    { q: "How much do I pay to confirm the booking?", a: "A deposit of roughly 15% to 20% of the total secures the reservation. The rest is settled directly with the rental agent when you pick up the car in Budva or at Tivat." },
    { q: "Can I rent without a credit card?", a: "Certain vehicles in the fleet can be rented with a debit card or without a card altogether. These are labelled in the search results so you can filter accordingly." },
  ],

  locations: [
    { name: "Budva Old Town", tag: "Most Popular" },
    { name: "Tivat Airport", tag: "22 km" },
    { name: "Bečići", tag: "" },
    { name: "Sveti Stefan", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "22 km Away",
      desc: "The closest airport to Budva. We meet you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Site",
      desc: "Medieval walled city, 25 km from Budva.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "Home Base",
      desc: "Old Town, beaches, and the heart of the riviera.",
      image: "/img/budva-old-town.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport, 65 km away.",
      image: "/img/montenegro-driving.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "Marina Town",
      desc: "Porto Montenegro and stunning Boka Bay.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "Hidden Gem",
      desc: "Baroque village on the Bay of Kotor.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Budva.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's modern capital — culture and commerce.",
      image: "/img/montenegro-driving.webp",
    },
  ],
};

export default siteConfig;
